DevOrg/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Associated_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Relationship</label>
        <referenceTo>Relationship__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Child_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DevOrg/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship</label>
        <referenceTo>Relationship__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

DevOrg/src/objects/Relationship__c.object
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/src/classes/ReassignPRAController.cls
public class ReassignPRAController{
    
    public string urlparm{get;set;}
    public string returl{get;set;}
    private string RelationshipId{get;set;}
    public List<String> rellist = new List<String>(); 
    private Relationship__c RelationshipOwnerId{get;set;}
    Id RelationshipOwner;
    Pagereference pageref;
    
        public ReassignPRAController(ApexPages.StandardController controller){
                    
        	Map<String, String> UrlParameterMap = ApexPages.currentPage().getParameters();
        	System.Debug('UrlParameterMap:'+UrlParameterMap.get('urlparm'));
        	System.Debug('retURL:'+UrlParameterMap.get('retURL'));  
        	RelationshipId = UrlParameterMap.get('urlparm');
            System.Debug('Values in Map:'+ RelationshipId);
            
            
            for(string str: RelationshipId.split(',')){
                
                rellist.add(str);
            }
            System.Debug('Values in String List:'+ rellist);
            RelationshipOwnerId = (Relationship__c)controller.getRecord();
            //System.Debug('Values of new Owner:'+ RelationshipOwnerId);
            
            List<Relationship__c> rel = [Select id, Name from Relationship__c where Id in :rellist];
            
        }
    
    public PageReference Save(){
        
        RelationshipOwner = RelationshipOwnerId.OwnerId;
        System.Debug('Values of new Owner:'+ RelationshipOwner);
        List<Relationship__c> listRelationship = [Select id, Name, OwnerId,
                                                 (Select Id, OwnerId from Opportunities__r),
                                                 (Select Id, OwnerId from Cases__r)
                                                  from Relationship__c where Id IN :rellist];
        
        return pageref;
    }

}